### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by barczaG** [Epharmix/Toureiro#10]
Hello guys,

While I'm using toureiro I get random json parse errors:
```
    at Object.parse (native)
    at Function.Job.fromData (/usr/lib/node_modules/toureiro/node_modules/bull/lib/job.js:544:40)
    at /usr/lib/node_modules/toureiro/node_modules/bull/lib/job.js:46:18
    at tryCatcher (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/toureiro/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```
the trace is not very helpful so I couldn't figure out the root of the problem.

**Comment by evanhuang8** [comment]
This is actually an error from the `bull` library itself, likely because of the job data is corrupted. I recommend you filing a ticket there - if memory serves I have seen people with similar problems before and filed tickets, so you may be able to find a solution there.

Since my theory is data corruption, maybe you can look into the raw data in redis using `redis-commander` or similar and see what's messed up.

**Comment by tshelburne** [comment]
@barczaG If you are working with Python-backed services, often times this may mean that Python is throwing an error somewhere - in Python, a unicode string represented as a literal may be outputted as `u'some error string'`. If that's the case, it might mean that you are receiving a non-json error from the service with a unicode string being output. Otherwise, it could be just like @evanhuang8 mentioned.

I've seen these things crop up on our side because many of our microservices are written in Python.

**Comment by evanhuang8** [comment]
I actually added some handling to handle this situation in the newest update, take a look!
