### ISSUE TITLE
Cannot call method 'getState' of null

### ISSUE THREAD

**Issue by carsol** [Epharmix/Toureiro#4]
First off, thank you! This is exactly what we need 😄  

One issue is that we can't see **Active** jobs. I get this error when I attempt to go to that page. All other pages work!

```
TypeError: Cannot call method 'getState' of null
    at /home/ubuntu/toureiro-queues/lib/models/job.js:111:22
    at arrayMap (/home/ubuntu/toureiro-queues/node_modules/lodash/index.js:1406:25)
    at Function.map (/home/ubuntu/toureiro-queues/node_modules/lodash/index.js:6710:14)
    at /home/ubuntu/toureiro-queues/lib/models/job.js:110:30
    at tryCatcher (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:629:18)
    at PromiseArray._resolve (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:565:26)
    at Promise._settlePromise0 (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/promise.js:629:18)
    at Command.callback (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/bluebird/js/release/nodeback.js:42:21)
    at normal_reply (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/redis/index.js:620:21)
    at RedisClient.return_reply (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/redis/index.js:719:9)
    at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/redis/index.js:154:18)
    at JavascriptReplyParser.run (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/redis/node_modules/redis-parser/lib/javascript.js:137:18)
    at JavascriptReplyParser.execute (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/redis/node_modules/redis-parser/lib/javascript.js:112:10)
    at Socket.<anonymous> (/home/ubuntu/toureiro-queues/node_modules/bull/node_modules/redis/index.js:240:27)
```

**Comment by evanhuang8** [comment]
```javascript
    if (type === 'wait' || type === 'active') {
      return q.getJobs(type, 'LIST', offset, offset + limit - 1).then(function(jobs) {
        return Promise.all(_.map(jobs, function(job) {
          return job.getState().then(function(state) {
            job.state = state;
            return job;
          });
        }));
      });
    }
```

The error is in `job.getState`, and it appears that the job is `null`. Any chance you can log out the `jobs` before the `return Promise.all...` line, and see why will there be a `null` job in the list?

**Comment by carsol** [comment]
Ah your suspicious is correct. What can we do to remove those jobs that are `null`? Sadly we have more then a couple in a production environment.

Your project was a great help for us to discover that this was a problem for us. Thank you for that.
